### ISSUE TITLE
gradle distribution fails

### ISSUE THREAD

**Issue by rafalkrupinski** [mwsobol/SORCER#5]
Download http://www.rio-project.org/maven2/org/rioproject/distribution/5.0/distribution-5.0.zip
:distribution:gatherDeps FAILED

FAILURE: Build failed with an exception.
- Where:
  Build file '/home/rufio/sorcer/SORCER/distribution/build.gradle' line: 119
- What went wrong:
  Execution failed for task ':distribution:gatherDeps'.
  
  > Could not resolve all dependencies for configuration ':distribution:distribution'.
  > Could not download artifact 'org.rioproject:distribution:5.0:distribution.zip'
  > Failed to download resource 'http://www.rio-project.org/maven2/org/rioproject/distribution/5.0/distribution-5.0.zip'.
  >      > Premature end of Content-Length delimited message body (expected: 26347449; received: 25144236
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by mwsobol** [comment]
Rafał, 

Nie wiem co robisz, przed chwilą sprawdziłem - nie żadnego problemu.
Ja pracuję w branch develop jak i moi studenci w mom wykładzie w PJATK, dzisiaj mam ostatni wykład.
Przełączylem się do master i jest OK.

Pierwszy krok jest zbudowanie dystrybucji, bez tego nic nie działa. A więc bo sklonowaniu SORCER-a z gitHub:

1. gradle dist
2. gradlle bootSorcer
3. gradle browser
4. cd examples/sml
5. gradle test
6. gradle terminateSorcer

Template dla zrobienia service jest w examples/service
Tutorials na project site: http://sorcersoft.org/project/site/ 

Pozdrawiam,
- ms

**Comment by rafalkrupinski** [comment]
`gradle dist` działa
`gradle distribution` nie działa

**Comment by mwsobol** [comment]
Rafał,

To jest ten sam task, ja używam skrótu “dist".

- ms

**Comment by rafalkrupinski** [comment]
To w takim razie gdzieś urywa, czasem distrybucja rio się ściąga, czasem nie. Paweł też to ma

**Comment by rafalkrupinski** [comment]
Problem pojawia się w dalszym ciągu, nie mogę zbudować dystrybucji. Proszę o naprawienie

**Comment by dreedyman** [comment]
This is unreproducable for me. Although sometimes a retry is required. Additionally, you seem to be using an outdated version of the project, since the latest depends on Rio 5.1.2

**Comment by rafalkrupinski** [comment]
When a retry isn't required? It would seem that rio distribution gets downloaded every time

**Comment by dreedyman** [comment]
The rio distribution does not get downloaded every time you build the sorcer distro, just if you do not have it. Once you have it, it just uses it.

**Comment by rafalkrupinski** [comment]
Sounds reasonable, only it never actually managed to build. I can download the file manually, maybe you could tell me where to put it?

**Comment by mwsobol** [comment]
Szanowny Pan
Radny m. st. Warszawy

W imieniu własnym jak również mojej córki Moniki zwracam się do Pana z uprzejmą prośba o wyrażenie zgody  na wykorzystanie w nazewnictwie miejskim Miasta Stołecznego Warszawy proponowanej nazwy – LAS IRENY JAROCKIEJ (załącznik nr. 1) wpisanej do Banku Nazw (załącznik nr. 2, Pismo z Biura Kultury Urzędu m.st. Warszawy z dnia 26 maja 2014 r.). 

Pełny tekst prośby wraz ze spójnym zestawem załączników w załączeniu. Załączniki te wskazują na pozytywną opinię formalnie procedowaną prawie trzy lata temu i potwierdzoną pismem Biura Kultury Urzędu Miasta Warszawy o wpisaniu nazwiska Ireny Jarockiej do Banku Nazw.

Pozdrawiam serdecznie,
Michał Sobolewski
https://pl.wikipedia.org/wiki/Michał_Władysław_Sobolewski
